# Generated by Django 2.0.7 on 2019-07-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_id', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('checked', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
