# Generated by Django 2.0.7 on 2019-07-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
