# Generated by Django 2.2.2 on 2019-07-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20190717_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
