# Generated by Django 2.2.2 on 2019-07-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20190718_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Dev\\venv\\src\\static'),
        ),
    ]
