# Generated by Django 2.2.2 on 2019-07-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_nfmc_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nfmc_step',
            field=models.ManyToManyField(related_name='step', to='training_manuals.Training_Manual'),
        ),
    ]
