# Generated by Django 2.2.2 on 2019-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20190718_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
